/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppAppsAppIdRouteImport } from './routes/_app/apps/$appId'
import { Route as AppAppsAppIdIndexRouteImport } from './routes/_app/apps/$appId/index'
import { Route as AppAppsAppIdAudiencesRouteImport } from './routes/_app/apps/$appId/audiences'
import { Route as AppAppsAppIdDeploymentsRouteImport } from './routes/_app/apps/$appId/deployments'
import { Route as AppAppsAppIdExplainRouteImport } from './routes/_app/apps/$appId/explain'
import { Route as AppAppsAppIdPoliciesRouteImport } from './routes/_app/apps/$appId/policies'
import { Route as AppAppsAppIdSettingsRouteImport } from './routes/_app/apps/$appId/settings'
import { Route as AppAppsAppIdReleasesIndexRouteImport } from './routes/_app/apps/$appId/releases/index'
import { Route as AppAppsAppIdReleasesReleaseIdRouteImport } from './routes/_app/apps/$appId/releases/$releaseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppIdRoute = AppAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppIdIndexRoute = AppAppsAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdAudiencesRoute = AppAppsAppIdAudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdDeploymentsRoute = AppAppsAppIdDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdExplainRoute = AppAppsAppIdExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdPoliciesRoute = AppAppsAppIdPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdSettingsRoute = AppAppsAppIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdReleasesIndexRoute =
  AppAppsAppIdReleasesIndexRouteImport.update({
    id: '/releases/',
    path: '/releases/',
    getParentRoute: () => AppAppsAppIdRoute,
  } as any)
const AppAppsAppIdReleasesReleaseIdRoute =
  AppAppsAppIdReleasesReleaseIdRouteImport.update({
    id: '/releases/$releaseId',
    path: '/releases/$releaseId',
    getParentRoute: () => AppAppsAppIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/users': typeof AppUsersRoute
  '/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/apps/$appId/audiences': typeof AppAppsAppIdAudiencesRoute
  '/apps/$appId/deployments': typeof AppAppsAppIdDeploymentsRoute
  '/apps/$appId/explain': typeof AppAppsAppIdExplainRoute
  '/apps/$appId/policies': typeof AppAppsAppIdPoliciesRoute
  '/apps/$appId/settings': typeof AppAppsAppIdSettingsRoute
  '/apps/$appId/': typeof AppAppsAppIdIndexRoute
  '/apps/$appId/releases/$releaseId': typeof AppAppsAppIdReleasesReleaseIdRoute
  '/apps/$appId/releases/': typeof AppAppsAppIdReleasesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/apps/$appId/audiences': typeof AppAppsAppIdAudiencesRoute
  '/apps/$appId/deployments': typeof AppAppsAppIdDeploymentsRoute
  '/apps/$appId/explain': typeof AppAppsAppIdExplainRoute
  '/apps/$appId/policies': typeof AppAppsAppIdPoliciesRoute
  '/apps/$appId/settings': typeof AppAppsAppIdSettingsRoute
  '/apps/$appId': typeof AppAppsAppIdIndexRoute
  '/apps/$appId/releases/$releaseId': typeof AppAppsAppIdReleasesReleaseIdRoute
  '/apps/$appId/releases': typeof AppAppsAppIdReleasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/_app/apps/$appId/audiences': typeof AppAppsAppIdAudiencesRoute
  '/_app/apps/$appId/deployments': typeof AppAppsAppIdDeploymentsRoute
  '/_app/apps/$appId/explain': typeof AppAppsAppIdExplainRoute
  '/_app/apps/$appId/policies': typeof AppAppsAppIdPoliciesRoute
  '/_app/apps/$appId/settings': typeof AppAppsAppIdSettingsRoute
  '/_app/apps/$appId/': typeof AppAppsAppIdIndexRoute
  '/_app/apps/$appId/releases/$releaseId': typeof AppAppsAppIdReleasesReleaseIdRoute
  '/_app/apps/$appId/releases/': typeof AppAppsAppIdReleasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/audit'
    | '/users'
    | '/apps/$appId'
    | '/apps/$appId/audiences'
    | '/apps/$appId/deployments'
    | '/apps/$appId/explain'
    | '/apps/$appId/policies'
    | '/apps/$appId/settings'
    | '/apps/$appId/'
    | '/apps/$appId/releases/$releaseId'
    | '/apps/$appId/releases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/audit'
    | '/users'
    | '/'
    | '/apps/$appId/audiences'
    | '/apps/$appId/deployments'
    | '/apps/$appId/explain'
    | '/apps/$appId/policies'
    | '/apps/$appId/settings'
    | '/apps/$appId'
    | '/apps/$appId/releases/$releaseId'
    | '/apps/$appId/releases'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/account'
    | '/_app/audit'
    | '/_app/users'
    | '/_app/'
    | '/_app/apps/$appId'
    | '/_app/apps/$appId/audiences'
    | '/_app/apps/$appId/deployments'
    | '/_app/apps/$appId/explain'
    | '/_app/apps/$appId/policies'
    | '/_app/apps/$appId/settings'
    | '/_app/apps/$appId/'
    | '/_app/apps/$appId/releases/$releaseId'
    | '/_app/apps/$appId/releases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appId': {
      id: '/_app/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppAppsAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appId/': {
      id: '/_app/apps/$appId/'
      path: '/'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof AppAppsAppIdIndexRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/audiences': {
      id: '/_app/apps/$appId/audiences'
      path: '/audiences'
      fullPath: '/apps/$appId/audiences'
      preLoaderRoute: typeof AppAppsAppIdAudiencesRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/deployments': {
      id: '/_app/apps/$appId/deployments'
      path: '/deployments'
      fullPath: '/apps/$appId/deployments'
      preLoaderRoute: typeof AppAppsAppIdDeploymentsRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/explain': {
      id: '/_app/apps/$appId/explain'
      path: '/explain'
      fullPath: '/apps/$appId/explain'
      preLoaderRoute: typeof AppAppsAppIdExplainRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/policies': {
      id: '/_app/apps/$appId/policies'
      path: '/policies'
      fullPath: '/apps/$appId/policies'
      preLoaderRoute: typeof AppAppsAppIdPoliciesRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/settings': {
      id: '/_app/apps/$appId/settings'
      path: '/settings'
      fullPath: '/apps/$appId/settings'
      preLoaderRoute: typeof AppAppsAppIdSettingsRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/releases/': {
      id: '/_app/apps/$appId/releases/'
      path: '/releases'
      fullPath: '/apps/$appId/releases/'
      preLoaderRoute: typeof AppAppsAppIdReleasesIndexRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/releases/$releaseId': {
      id: '/_app/apps/$appId/releases/$releaseId'
      path: '/releases/$releaseId'
      fullPath: '/apps/$appId/releases/$releaseId'
      preLoaderRoute: typeof AppAppsAppIdReleasesReleaseIdRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
  }
}

interface AppAppsAppIdRouteChildren {
  AppAppsAppIdAudiencesRoute: typeof AppAppsAppIdAudiencesRoute
  AppAppsAppIdDeploymentsRoute: typeof AppAppsAppIdDeploymentsRoute
  AppAppsAppIdExplainRoute: typeof AppAppsAppIdExplainRoute
  AppAppsAppIdPoliciesRoute: typeof AppAppsAppIdPoliciesRoute
  AppAppsAppIdSettingsRoute: typeof AppAppsAppIdSettingsRoute
  AppAppsAppIdIndexRoute: typeof AppAppsAppIdIndexRoute
  AppAppsAppIdReleasesReleaseIdRoute: typeof AppAppsAppIdReleasesReleaseIdRoute
  AppAppsAppIdReleasesIndexRoute: typeof AppAppsAppIdReleasesIndexRoute
}

const AppAppsAppIdRouteChildren: AppAppsAppIdRouteChildren = {
  AppAppsAppIdAudiencesRoute: AppAppsAppIdAudiencesRoute,
  AppAppsAppIdDeploymentsRoute: AppAppsAppIdDeploymentsRoute,
  AppAppsAppIdExplainRoute: AppAppsAppIdExplainRoute,
  AppAppsAppIdPoliciesRoute: AppAppsAppIdPoliciesRoute,
  AppAppsAppIdSettingsRoute: AppAppsAppIdSettingsRoute,
  AppAppsAppIdIndexRoute: AppAppsAppIdIndexRoute,
  AppAppsAppIdReleasesReleaseIdRoute: AppAppsAppIdReleasesReleaseIdRoute,
  AppAppsAppIdReleasesIndexRoute: AppAppsAppIdReleasesIndexRoute,
}

const AppAppsAppIdRouteWithChildren = AppAppsAppIdRoute._addFileChildren(
  AppAppsAppIdRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAuditRoute: typeof AppAuditRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAppsAppIdRoute: typeof AppAppsAppIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAuditRoute: AppAuditRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppAppsAppIdRoute: AppAppsAppIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
